FROM golang:1.26-alpine

WORKDIR /app

# Install git and Air + Swag
RUN apk add --no-cache git \
    && go install github.com/air-verse/air@latest \
    && go install github.com/swaggo/swag/cmd/swag@latest

# Copy dependencies first for caching
COPY go.mod go.sum ./
RUN go mod download

# Copy application source code
COPY . .

EXPOSE 8000

# Run Air live reloader
CMD ["air", "-c", ".air.toml"]