basePath: /
definitions:
  models.CreateTaskRequest:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  models.TaskResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      title:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  description: A simple task API written in Go.
  title: Task API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate the user and set a Cookie
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged in
        "400":
          description: Invalid JSON payload
          schema:
            type: string
        "401":
          description: Incorrect email address or password
          schema:
            type: string
        "500":
          description: Failed to create access token
          schema:
            type: string
      summary: Log a user in
      tags:
      - public
  /auth/logout:
    post:
      description: Delete the current user session Cookie
      produces:
      - application/json
      responses:
        "200":
          description: Successfully logged out
      summary: Log a user out
      tags:
      - public
  /auth/register:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Successfully Created
        "400":
          description: Bad Request. Possible causes:<br>• <b>Invalid JSON payload</b><br>•
            <b>Email registered</b>
          schema:
            type: string
        "500":
          description: Internal Server Error. Possible causes:<br>• <b>Internal Server
            Error</b><br>• <b>Failed to hash password</b><br>• <b>Failed to create
            user</b>
          schema:
            type: string
      summary: Register a user
      tags:
      - public
  /tasks:
    post:
      consumes:
      - application/json
      description: Create a new task
      parameters:
      - description: Task
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/models.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.TaskResponse'
        "400":
          description: Invalid request body
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
        "500":
          description: Unable to create the task
          schema:
            type: string
      summary: Create a task
      tags:
      - tasks
swagger: "2.0"
